-- Dashboard tables for Fundastock WhatsApp bot analytics
-- Run against Supabase direct connection:
--   psql "postgresql://postgres:[PASSWORD]@db.[PROJECT].supabase.co:5432/postgres" -f migrations/002_dashboard.sql

-- Annotations written while reviewing conversations
CREATE TABLE IF NOT EXISTS conversation_annotations (
  id BIGSERIAL PRIMARY KEY,
  phone_number TEXT NOT NULL,
  turn_id BIGINT REFERENCES sales_conversation_turns(id) ON DELETE SET NULL,
  category TEXT NOT NULL,          -- 'bad_response' | 'missed_upsell' | 'good_close' | 'prompt_gap' | 'tool_failure' | 'other'
  severity TEXT,                   -- 'low' | 'medium' | 'high'
  note TEXT,
  suggested_prompt_change TEXT,
  created_by TEXT DEFAULT 'horacio',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ca_phone ON conversation_annotations(phone_number);
CREATE INDEX IF NOT EXISTS idx_ca_category ON conversation_annotations(category);
CREATE INDEX IF NOT EXISTS idx_ca_created ON conversation_annotations(created_at DESC);

-- Pre-aggregated daily campaign metrics (refreshed hourly)
CREATE TABLE IF NOT EXISTS daily_campaign_metrics (
  date DATE,
  campaign_id TEXT,
  lead_source TEXT,
  conversations_started INT DEFAULT 0,
  conversations_qualified INT DEFAULT 0,
  orders_created INT DEFAULT 0,
  payment_claimed INT DEFAULT 0,
  payment_paid INT DEFAULT 0,
  escalated INT DEFAULT 0,
  human_takeover INT DEFAULT 0,
  gross_revenue NUMERIC DEFAULT 0,
  median_turns_to_close INT,
  median_minutes_to_close INT,
  last_refreshed TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (date, campaign_id)
);

-- Manual ad spend entry (filled weekly from Meta/TikTok ads manager)
CREATE TABLE IF NOT EXISTS manual_ad_spend (
  id BIGSERIAL PRIMARY KEY,
  date DATE NOT NULL,
  campaign_id TEXT NOT NULL,
  spend_mxn NUMERIC NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (date, campaign_id)
);
CREATE INDEX IF NOT EXISTS idx_mas_date ON manual_ad_spend(date DESC);

-- Daily review reports generated by Claude analysis
CREATE TABLE IF NOT EXISTS daily_review_reports (
  id BIGSERIAL PRIMARY KEY,
  date DATE NOT NULL UNIQUE,
  conversations_reviewed INT DEFAULT 0,
  report_markdown TEXT,
  source_phone_numbers TEXT[],     -- phones included in the analysis
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_drr_date ON daily_review_reports(date DESC);
